spring:
  datasource:
    url: jdbc:postgresql://ep-bold-voice-an1gyki7-pooler.c-6.us-east-1.aws.neon.tech:5432/neondb?sslmode=require
    username: neondb_owner
    password: npg_y0ZvxQnd2tLB

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

app:
  jwt:
    secret: my-super-secret-key-very-long-123456789
    issuer: bookstore-backend
    expiration-minutes: 60