spring:
  profiles:
    active: local
  application:
    name: backend
#  profiles:
#    active: local
#  datasource:
#    url: jdbc:postgresql://localhost:5432/BOOKSTORE_DB?timezone=Asia/Ho_Chi_Minh
#    username: postgres
#    password: 240206
#  driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#app:
#  jwt:
#    # Chuỗi secret này dùng để mã hóa Token, phải đủ dài (ít nhất 32 ký tự)
#    secret: "DayLaChuoiBiMatSieuCapVipProChoBookStore2026!@#"
#    issuer: "BookStoreBackend"
#    expiration-minutes: 60