version: '3.8'

services:
  postgres_db:
    image: postgres:15
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: bookstore
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer:latest
    container_name: bookstore_adminer
    restart: always
    ports:
      - "5050:8080"
    depends_on:
      - postgres_db
volumes:
  postgres_data: